services:
  nextjs-app:
    image: 182491688958.dkr.ecr.ca-central-1.amazonaws.com/personal-web:latest  # Specify the image you want to use
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3003
      HOSTNAME: "0.0.0.0"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      GOOGLE_TOKEN: ${GOOGLE_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped